# Generated by Django 3.2 on 2021-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blogtitle', models.TextField(default='', max_length=300)),
                ('name', models.TextField(max_length=50)),
                ('blogsubtitle', models.TextField(default='', max_length=200)),
                ('blogcontent', models.TextField(default='')),
                ('pub_date', models.DateField(null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
